version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: osrs-ge-postgresql-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - osrs-ge-postgresql-prod-data:/var/lib/postgresql/data

volumes:
  osrs-ge-postgresql-prod-data:
